version: '3.9'

services:
  backend:
    build: .
    container_name: statusneo_backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev